version: '3.0'

services:
  grafana:
    container_name: 'grafana-deep-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.2.0}
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
    ports:
      - '3000:3000' # this needs to be 3000 for e2e tests
      - '3222:3222' # this is for delve debugger
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/root/dev
      - ./dist:/var/lib/grafana/plugins/intergral-deep-datasource
      - ~/repo/github/intergral/grafana-deep-panel/dist:/var/lib/grafana/plugins/intergral-deep-panel
      - ~/repo/github/intergral/grafana-deep-tracepoint-panel/dist:/var/lib/grafana/plugins/grafana-deep-tracepoint-panel
      - ./provisioning:/etc/grafana/provisioning
