site_name: Deep Grafana Datasource
site_url: https://intergral.github.com/grafana-deep-datasource/

repo_name: Grafana Deep Datasource
repo_url: https://github.com/intergral/grafana-deep-datasource

edit_uri_template: /intergral/grafana-deep-datasource/edit/master/docs/docs/{path}

copyright: Intergral GmbH 2023

site_dir: _site

theme:
  logo: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.png?raw=true
  favicon: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.svg?raw=true
  name: material
  features:
    - content.code.copy
    - content.action.edit

extra_css:
  - styles/styles.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search:
  - spellcheck:
      backends: # the backends you want to use
        - symspellpy  # as strings
        - codespell: # or nested configs
            dictionaries: [ clear, code, names  ]

      # known_words can also be a list of words
      known_words: known_words.txt

      # ignore words in <code> tags
      ignore_code: yes

      # minimum length of words to consider
      min_length: 2

      # maximum number of capital letters in a word
      max_capital: 1

      # keep unicode characters
      allow_unicode: no

      # skip files entirely
      skip_files:
        - credits.md
        - coverage.md

      # whether to only check in strict mode
      strict_only: no